Presentacion/Controllers/DetalleVentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class DetalleVentaController : Controller
    {
        // GET: DetalleVenta
       
        public ActionResult Mostrar(int IdVenta)
        {
           
            Atributos.DetalleVenta ventaProducto = new Atributos.DetalleVenta();
            Atributos.Result result = LogicaNegocio.DetalleVenta.DetalleVentaIdVenta(IdVenta);
            
            Atributos.Result resultStock = new Atributos.Result();
            
            if (result.Correct)
            {
                ventaProducto.DetalleVentas = result.Objects;
                return View("Detalle", ventaProducto);
               
            }

            else
            {
                ViewBag.Message = "Ocurrio un error al traer la informacion" + result.ErrorMessage;
            }

            return View("Detalle", ventaProducto);
        }
    }
}

Presentacion/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class VentaController : Controller
    {
		// GET: Venta
		[HttpGet]
		public ActionResult MostrarProductos() //Muestra los Productos que el usuario puede comprar
		{

			Atributos.Result result = LogicaNegocio.Producto.MostrarTodo(); //LLama a al metodo de productos para mostrar todos los productos existentes
			Atributos.Producto producto = new Atributos.Producto(); //Nueva instanci de Producto

			if (result.Correct)
			{
			    producto.Productos = result.Objects; //Unboxing de todos los productos
				return View(producto); //Mandamos a la vista la lista de objetos de productos
			}
			else
			{
				ViewBag.Message = "Ocurrió un error al obtener la información" + result.ErrorMessage; //Mensaje de Error
				return PartialView("Modal"); //Vista modal en caso de algun Error
			}

		}

		[HttpGet]
		public ActionResult Carrito(int? IdProducto)   //Metodo Carrito puede recibir un IdProducto o no
		{
			Atributos.Result result = new Atributos.Result();
			result.Objects = new List<object>();
			if (IdProducto != null)     //si IdProducto viene en null
			{
				if (Session["Carrito"] == null)  //Si el carrito no tiene productos agregados
				{

					Atributos.DetalleVenta  ventaProducto = new Atributos.DetalleVenta(); 

					ventaProducto.Producto = new Atributos.Producto();
					ventaProducto.Producto.IdProducto = IdProducto.Value; //Evaluar el del Producto

					ventaProducto.Cantidad = 1; //Inicializar Cantidad 

					Atributos.Result resultProducto = LogicaNegocio.Producto.MostrarUno(IdProducto.Value); //Traer los datos de el producto selccionado en el carrito

					if (resultProducto.Correct)
					{
						ventaProducto.Producto = (Atributos.Producto)resultProducto.Object; //Unboxing de los datos del producto selccionado

						result.Objects.Add(ventaProducto); //Mandar los datos a la vista
					}

					Session["Carrito"] = result.Objects;
				}

				else //En caso que el carrito tenga ya productos selccionados
				{
					result.Objects = (List<Object>)Session["Carrito"];

					bool Existe = false;
					var indice = 0;

					foreach (Atributos.DetalleVenta ventaProducto in result.Objects) //Recorrer los productos selccionados
					{
						if (ventaProducto.Producto.IdProducto == IdProducto)
						{
							Existe = true;
							indice = result.Objects.IndexOf(ventaProducto);

						}
					}

					if (Existe == true) //Si  existe el producto en el carrito
					{
						foreach (Atributos.DetalleVenta ventaProducto in result.Objects)
						{
							ventaProducto.Cantidad = ventaProducto.Cantidad + 1; //Aumentar 1 a la cantidad de el producto
						}
					}
					else //En caso de que no este seleccionado en el carrito 
					{

						Atributos.DetalleVenta ventaProducto = new Atributos.DetalleVenta();

						ventaProducto.Producto = new Atributos.Producto();
						ventaProducto.Producto.IdProducto = IdProducto.Value;
						ventaProducto.Cantidad = 1;


						Atributos.Result resultProducto = LogicaNegocio.Producto.MostrarUno(IdProducto.Value);

						if (resultProducto.Correct)
						{
							ventaProducto.Producto = (Atributos.Producto)resultProducto.Object;

							result.Objects.Add(ventaProducto); //Mandara los datos del nuevo producto al carrito

						}

						Session["Carrito"] = result.Objects;

					}

				}
			}

			return View(result);
		}

		public ActionResult Sumar(int IdProducto)
		{
			Atributos.Result result = new Atributos.Result();

			result.Objects = (List<Object>)Session["Carrito"];//Unboxing de la lista

			foreach (Atributos.DetalleVenta ventaProducto in result.Objects) //para comparar
			{
				if (ventaProducto.Producto.IdProducto == IdProducto)
				{

					ventaProducto.Cantidad += 1;//Aumenta la cantidad en 1

				}
			}
			return View("Carrito", result);
		} // Metodo que le agrega 1 a la Cantidad del producto en la lista de Venta 

		public ActionResult Restar(int IdProducto)
		{
			Atributos.Result result = new Atributos.Result();

			result.Objects = (List<Object>)Session["Carrito"];//Unboxing de la Lista en el Carrito

			foreach (Atributos.DetalleVenta ventaProducto in result.Objects) 
			{

				if (ventaProducto.Producto.IdProducto == IdProducto)
				{
					ventaProducto.Cantidad -= 1; //Resta uno a la cantidad mostrada en el carrito
				}
			}
			return View("Carrito", result);
		}

		public ActionResult Eliminar(int IdProducto) //Eliminar producto seleccionado del Carrito
		{
			Atributos.Result result = new Atributos.Result();
			result.Objects = (List<Object>)Session["Carrito"];

			var indice = 0; 

			foreach (Atributos.DetalleVenta ventaProducto in result.Objects)
			{
				if (ventaProducto.Producto.IdProducto == IdProducto)
				{

					indice = result.Objects.IndexOf(ventaProducto);

				}
			}

			result.Objects.RemoveAt(indice);
			Session["Carrito"] = result.Objects;

			return View("Carrito", result);
		}

		public decimal GetTotal(List<object> Objects) //Calcular la Cantidad Total de Precio de los Prodcutos Seleccionados
		{
			decimal Total = 0;

			foreach (Atributos.DetalleVenta ventaProducto in Objects)
			{
				Total += ventaProducto.Producto.Precio * ventaProducto.Cantidad;
			}

			return Total;
		} 
		public ActionResult Procesar() //Realizar el Proceso de la Compra
		{

			Atributos.Result result = new Atributos.Result();
			result.Objects = (List<Object>)Session["Carrito"];

			Atributos.Venta venta = new Atributos.Venta();

			venta.Usuario = new Atributos.Usuario();
			venta.Usuario.IdUsuario = 1;

			venta.MetodoPago = new Atributos.MetodoPago();
			venta.MetodoPago.IdMetodoPago = 1;

			venta.Total = GetTotal(result.Objects);

			result = LogicaNegocio.Venta.Agregar(venta, result.Objects);


			return RedirectToAction("Mostrar","DetalleVenta", new { IdVenta = venta.IdVenta });
			Session.Clear();

		} 

		public ActionResult ModalCompra()  //Modal de Confirmacion de Compra
		{
			
			ViewBag.Message = "¿Deseas Finalizar tu compra?";
			return PartialView("Modal");
		}

	}
}

Presentacion/Views/DetalleVenta/Detalle.cshtml
@model Atributos.DetalleVenta
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2>Detalle</h2>
    </div>


    <div class="row">
        <div class="col-md-12">
            <h5>Detalle de la Venta</h5>
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div style="float:right">        
                @*@Html.ActionLink("Volver a comprar","MostrarProductos","Venta", htmlAttributes: new { @class = "btn btn-success" })*@
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <td class="hidden">IdProducto</td>
                    <td class="text-center" style=" font-weight:bold;">Nombre</td>
                    <td class="text-center" style=" font-weight:bold;">Precio Unitario</td>    
                    <td class="text-center" style=" font-weight:bold;">Descripción</td>
                    <td class="text-center" style=" font-weight:bold;">Imagen</td>
                    <td class="text-center" style=" font-weight:bold;">Cantidad</td>
                    <td class="text-center" style=" font-weight:bold;">SubTotal</td>
                    <td class="text-center" style=" font-weight:bold;">Total</td>
                </tr>
            </thead>
            <tbody>
                @foreach (Atributos.DetalleVenta ventaProducto in Model.DetalleVentas)
                {
                    <tr>
                        <td class="hidden">@ventaProducto.Producto.IdProducto</td>
                        <td>@ventaProducto.Producto.Nombre</td>
                        <td class="text-center">@ventaProducto.Producto.Precio</td>                    
                        <td>@ventaProducto.Producto.Descripcion</td>
                        @if (ventaProducto.Producto.Imagen != null)
                        {
                            <td class="text-center"><img src="data:image/jpeg;base64,@Convert.ToBase64String(ventaProducto.Producto.Imagen)" style=" height:150px; width: 150px;" /></td>
                        }
                        else
                        {
                            <td class="text-center"><img src="~/Content/SIN-IMAGEN.jpg" style=" height:150px; width:150px;" /></td>
                        }
                        <td> <a style="margin-left:15px; margin-right:15px;"> @ventaProducto.Cantidad</a> </td>

                        <td class="text-center">$ @(ventaProducto.Producto.Precio * ventaProducto.Cantidad)</td>
                        <td class="text-center">@ventaProducto.Venta.Total</td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>