Presentacion/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
      
        public ActionResult Mostrar() 
        {
            Atributos.Sucursal sucursal = new Atributos.Sucursal();
            Atributos.Result result = LogicaNegocio.Sucursal.MostrarTodo();
            if (result.Correct)
            {
                sucursal.Sucursales = result.Objects;
                return View(sucursal);
            }
            else
            {
                ViewBag.Message = "Ocurrio un Error";
            }
            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult Formulario(int? IdSucursal)
        {
            Atributos.Sucursal sucursal = new Atributos.Sucursal();
            Atributos.Result result = new Atributos.Result();

            if (IdSucursal == null)
            {

                return View(sucursal);
            }
            else
            {

                result = LogicaNegocio.Sucursal.MostrarUno(IdSucursal.Value);
                if (result.Correct)
                {
                    sucursal = (Atributos.Sucursal)result.Object;

                    return View(sucursal);
                }
            }
            return PartialView("Modal");
        }

        [HttpPost]
        public ActionResult Formulario(Atributos.Sucursal sucursal)
        {
            Atributos.Result result = new Atributos.Result();
     
            if (sucursal.IdSucursal == 0)
            {
                result = LogicaNegocio.Sucursal.Agregar(sucursal);
                if (result.Correct)
                {
                    ViewBag.Message = "Sucursal Ingresada Correctamente";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un Error al Registrar la nueva Sucursal";
                }
            }
            else
            {
                result = LogicaNegocio.Sucursal.Actualizar(sucursal);
                if (result.Correct)
                {
                    ViewBag.Message = "Actualizacion Exitosa";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un Error al Actualizar";
                }
            }
            return PartialView("Modal");
        }

        public ActionResult Eliminar(int IdSucursal)
        {
            Atributos.Result result = LogicaNegocio.Sucursal.Eliminar(IdSucursal);
            if (result.Correct)
            {
                ViewBag.Message = "Sucursal Eliminada Correctamente";
            }
            else
            {
                ViewBag.Message = "Ocurrio un Error al Eliminar la Sucursal";
            }
            return PartialView("Modal");
        }
    }
}

Presentacion/Views/Sucursal/Formulario.cshtml
@model Atributos.Sucursal
@{
    ViewBag.Title = "Formulario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Usuario</h1>
            <h5>Ingrese los Datos de Sucursal para registrar una nueva: </h5>
        </div>
    </div>

    @using (Html.BeginForm("Formulario", "Sucursal", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <div class="col-md-3">
                @Html.LabelFor(model => model.IdSucursal, new { @class = "hidden" })
                @Html.TextBoxFor(model => model.IdSucursal, new { @class = "hidden form-control" })
            </div>
        </div>
        <br />

            <div class="col-md-3">

                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @autocomplete = "off", @placeholder = "Nombre", @onkeypress = "return SoloLetras('event','LblNombreError')" })
                <label id="LblNombreError"></label>
            </div>
           
                <div class="col-md-3">

                    @Html.TextBoxFor(model => model.Direccion, new { @class = "form-control", @autocomplete = "off", @placeholder = "Direccion" })
                </div>

                <div class="col-md-3">
                    @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @autocomplete = "off", @placeholder = "Telefono", @onkeypress = "retun SoloLetras(event,'lblApellidoPaternoError')" })
                </div>

        <div class="form-group">
            <div class="col-md-3">
                <input type="submit" value="Guardar" class="btn btn-success" />
                @Html.ActionLink("Regresar", "Mostrar", "Sucursal", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    }
</div>

Presentacion/Views/Sucursal/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">   
                @Html.ActionLink("Regresar", "Mostrar", "Sucursal", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

Presentacion/Views/Sucursal/Mostrar.cshtml
@model Atributos.Sucursal
@{
    ViewBag.Title = "Mostrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Sucursales</h1>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h5>En esta vista puedes agregar una nueva sucursal, modificar alguna existente y elimar</h5>
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <p class="text-right">@Html.ActionLink("+", "Formulario", "Sucursal", htmlAttributes: new { @class = "btn btn-success" })</p>
        </div>
    </div>
    @if (Model.Sucursales.Count > 0 && Model.Sucursales != null)
    {
        <div class="row">
            <div class="col-md-12 text-center ">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr class="text-center">
                            <td>Editar</td>
                            <td class="hidden"> IdSucursal</td>
                            <td>Nombre</td>
                            <td>Direccion</td>
                            <td>Telefono</td>
                            <td>Eliminar</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Atributos.Sucursal sucursal in Model.Sucursales)
                        {
                            <tr class="align-content-center">
                                <td><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Formulario","Sucursal", new { IdSucursal = sucursal.IdSucursal })"></a></td>
                                <td class="hidden">@sucursal.IdSucursal</td>
                                <td>@sucursal.Nombre</td>
                                <td>@sucursal.Direccion</td>
                                <td>@sucursal.Telefono</td>
                                <td><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Eliminar", "Sucursal", new { IdSucursal = sucursal.IdSucursal})" onclick="return confirm ('Estas seguro que deseas borrar la Sucursal');"></a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    }
    else
    {
        <div class="alert alert-danger" role="alert">
            No se encontraron Datos
        </div>
    }
</div>